version: '3.5'
services:

  traefik:
    image: traefik:v2.1
    volumes:
      - ./certs/ca.pem:/etc/traefik/crt/ca.pem:ro
      - ./conf:/etc/traefik/conf
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --entrypoints.websecure.address=:443
      - --log.level=DEBUG
      - --api.insecure=true
      - --providers.docker
      - --providers.file.directory=/etc/traefik/conf
    ports:
      - '443:443'
      - '80:80'
      - '8080:8080'
    networks:
      - net

  server:
    image: golang:1.13.8-alpine3.11
    command: sh -c 'go get -d -v ./... && go install -v ./... && app'
    working_dir: /go/src/app
    volumes:
      - .:/go/src/app
    ports:
      - "5858:8080" # to access directly
    networks:
      net:
        aliases:
          - server

  api:
    image: containous/whoami
    labels:
      - traefik.port=80
      - traefik.http.routers.router0.entrypoints=websecure
      - traefik.http.routers.router0.tls=true
      - traefik.http.routers.router0.rule=Host(`whoami`)
      - traefik.http.routers.router0.middlewares=passcert@file,fauth@file
    networks:
      - net

networks:
  net:
    name: "net"
    driver: bridge
    ipam:
     config:
       - subnet: 10.0.1.0/28
