[tls.options]
  [tls.options.default]
    [tls.options.default.clientAuth]
      caFiles = ["/etc/traefik/crt/ca.pem"]
      clientAuthType = "RequireAndVerifyClientCert"

[http.middlewares.passcert.passTLSClientCert.info.subject]
    commonName = true

[http.middlewares.fauth.forwardauth]
    address="http://server:8080"
#    trustForwardHeader=true
